version: '3.8'

services:
  # Servicio principal de la aplicación (entorno de desarrollo)
  app:
    # **Ajuste clave:** Usamos la imagen específica de Go 1.23 para coincidir con la configuración del .devcontainer/devcontainer.json
    image: mcr.microsoft.com/devcontainers/go:1.23 
    volumes:
      # Mapea todo el repositorio al contenedor
      - .:/workspaces/Geochat:cached
    ports:
      # Mapeo de puertos para el backend (Go) y el frontend (Vue)
      - 8080:8080
      - 5173:5173
    depends_on:
      - db
    # Comando para iniciar la aplicación (ejecuta Go y Node en segundo plano)
    command: bash -c "go run Backend/main.go & npm run dev --prefix Frontend"
    
  # Servicio de PostgreSQL (Base de datos)
  db:
    image: postgres:15-alpine # Imagen ligera y estable
    restart: always
    environment:
      # Credenciales para que el servicio 'app' se conecte usando Host: 'db'
      POSTGRES_DB: geochat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # Persistencia de datos
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: